### ISSUE TITLE
data can't be downloaded

### ISSUE THREAD

**Issue by impactcolor** [Grzego/handwriting-generation#1]
The data on this link: data/original-xml-part.tar.gz cannot be downloaded it's asking for username and password credentials.  Is there another place where it can be found?

**Comment by Grzego** [comment]
I apologise for not making this more explicit. To download the dataset you need to register first on [this page](http://www.fki.inf.unibe.ch/databases/iam-on-line-handwriting-database) ("Download" section). After registration you will be able to download the [data/original-xml-part.tar.gz](http://www.fki.inf.unibe.ch/databases/iam-on-line-handwriting-database/download-the-iam-on-line-handwriting-database). :)

**Comment by impactcolor** [comment]
Thank you!
