### ISSUE TITLE
how to make black color of letters

### ISSUE THREAD

**Issue by designervoid** [Grzego/handwriting-generation#18]
so i've running this command
`python generate.py --noinfo --text="this was generated by computer" --bias=1.`
in readme.md (https://github.com/Grzego/handwriting-generation/raw/master/imgs/example-1.PNG) - result of this command
how i can get only black letters or blue letters on image after running of this command?

**Comment by Grzego** [comment]
Hi @designervoid,

Just add `color='blue'` or `color='black'` at [this line](https://github.com/Grzego/handwriting-generation/blob/master/generate.py#L203).

You should end up with:
```python
plt.plot(stroke[:, 0], -stroke[:, 1], color='black')
```
