### ISSUE TITLE
Random text being written after the input string

### ISSUE THREAD

**Issue by Belval** [Grzego/handwriting-generation#3]
It's quite a weird issue, not sure what might be causing it.

When I run the RNN to get the stroke data, it seems to add some garbage after my input string.

For example:

tsareva becomes [Imgur](https://i.imgur.com/XvAK0Lm.jpg)

Here's how I'm using the model: [TextRecognitionDataGenerator](https://github.com/Belval/TextRecognitionDataGenerator/blob/handwritten-generation/handwritten_text_generator.py)

**Comment by Grzego** [comment]
It seems like you forgot to include those lines:
```python
if finish[0, 0] > 0.8:
    break
```
at the end of `for` loop, after line [80](https://github.com/Belval/TextRecognitionDataGenerator/blob/handwritten-generation/handwritten_text_generator.py#L80). 

Small advice when using this model, add one space at the end of string you want to generate. I noticed that it sometimes cuts of last character without this space. :)

**Comment by Belval** [comment]
That did the trick! Thank you
